#!/usr/bin/env python3
import csv
import os
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
#from mcorr import fit_p2
from mcorr import fit_p2, read_corr, FitDatas, \
    write_fitting_results, plot_fit, plot_params, write_fitting_reports, \
    geom_r1, const_r1
from mcorr.fit import fit_model
from lmfit import fit_report

def main():
    """Run fitting using lmfit, and generate output files and plots"""
    parser = ArgumentParser(
        formatter_class=ArgumentDefaultsHelpFormatter,
        description="Infer recombination rates\
                    by fitting correlation profile of mutations.")
    parser.add_argument("corr_file", type = str, help='correlation input file')
    parser.add_argument("output_prefix", type=str, help='output file prefix')
    parser.add_argument('--fit_start', type=int, default=3,
                        help='fitting range starts at')
    parser.add_argument('--fit_end', type=int, default=300,
                        help='fitting range ends at')
    parser.add_argument("--use_geom_frag", action="store_true",
                        help='use geometric distribution for fragment sizes')
    parser.add_argument('--quiet', action="store_true")
    parser.add_argument("--title", type=str, help="plot title", default="")
    opts = parser.parse_args()
    corr_file = opts.corr_file
    prefix = opts.output_prefix
    fit_start = opts.fit_start
    fit_end = opts.fit_end
    quiet = opts.quiet
    use_geom_frag = opts.use_geom_frag
    title = opts.title

    ##for testing fixes
    # dir = '/Volumes/aps_timemachine/recombo/APS160.5_lmfit/cluster8_cluster221'
    # corr_file = os.path.join(dir, 'cluster8_cluster221_CORE_XMFA_OUT.csv')
    # prefix = 'cluster8_cluster221_FLEX_FIT_OUT'
    # fit_start = 3
    # fit_end = 300
    # quiet = False
    # use_geom_frag = False
    # title=""

    # read correlation results and prepare fitting data
    corr_results = read_corr(corr_file)
    fitdatas = FitDatas(corr_results, fit_start, fit_end)
    r1_func = const_r1
    ## write a fit report as generated by lmfit (includes chi-squared, uncertainties, etc)
    all = fitdatas.get("all")
    actualdata = fit_model(all.xvalues, all.yvalues, all.d_sample, r1_func)
    ## write a fit report as generated by lmfit (includes chi-squared, uncertainties, etc)
    params = actualdata.params.valuesdict()
    thetaS = actualdata.params["thetaS"]
    phiS = actualdata.params["phiS"]
    f = actualdata.params["f"]
    lmfitfile = prefix + "_lmfit_report.csv"
    with open(lmfitfile, "w+") as csvfile:
        lmfit_writer = csv.writer(csvfile, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        lmfit_writer.writerow(["fit_success", actualdata.success])
        lmfit_writer.writerow(["function_evals", actualdata.nfev])
        lmfit_writer.writerow(["data_points", actualdata.ndata])
        lmfit_writer.writerow(["variables", actualdata.nvarys])
        lmfit_writer.writerow(["message", actualdata.message])
        lmfit_writer.writerow(["thetaS (init)", thetaS.init_value])
        lmfit_writer.writerow(["f (init)", f.init_value])
        lmfit_writer.writerow(["phiS (init)", phiS.init_value])
        lmfit_writer.writerow([""])
        lmfit_writer.writerow(["d_s", "theta_s", "f", "phi_s",
                               "theta_p", "phi_p", "c", "d_theta_p",
                               "d_theta_s", "chisq", "red-chisq"])
        lmfit_writer.writerow([params["ds"], params["thetaS"], params["f"], params["phiS"],
                               params["thetaP"], params["phiP"], params["c"], params["dp"],
                               params["dc"], actualdata.chisqr, actualdata.redchi])

    #do fitting
    if use_geom_frag:
        r1_func = geom_r1
    fit_results = fit_p2(fitdatas, r1_func=r1_func, disable_progress_bar=quiet)
    # parameters to report
    model_params = ["group", "d_sample", "theta_pool",
                    "phi_pool", "ratio", "fbar", "c", "d_pool",
                    "d_clonal", 'theta_s', 'phi_s']
    # save fitting results into csv file
    csv_file = prefix + "_fit_results.csv"
    write_fitting_results(fit_results, model_params, csv_file)
    # plot the best fit
    best_fit_file = prefix + "_best_fit.svg"
    fitdata = fitdatas.get("all")
    fitres = None
    for res in fit_results:
        if res.group == "all":
            fitres = res
            break
    if fitres is not None:
        plot_fit(fitdata, fitres, best_fit_file, title=title)
    # write fitting report for bootstrapping
    report_file = prefix + "_bootstrapping_report.txt"
    write_fitting_reports(fit_results, model_params[1:7], report_file)
    ## write a fit report as generated by lmfit (includes chi-squared, uncertainties, etc)
    #print(fit_report(inpars=fitres))

    # plot histogram of fitted parameters
    # temporarily taking this out because it seems to be problematic
    # params_hist_file = prefix + "_parameter_histograms.svg"
    # plot_params(fit_results, model_params[1:7], params_hist_file)

if __name__ == "__main__":
    main()
